# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shisheo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shisheo
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'SDWebImage'

  target 'ShisheoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShisheoUITests' do
    # Pods for testing
  end

end
